/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chavezp7;

import java.text.DecimalFormat;

/**
 *
 * @author youracow
 */
public class InfoPanel extends javax.swing.JPanel {

    private double polyPerimeter;
    private double polygonArea;
    private double circumference;
    private double circleArea;
    private boolean showCircle;
    private DecimalFormat formatter = new DecimalFormat("###.####");

    public InfoPanel() {
        initComponents();
        update();
    }
    // <editor-fold defaultstate="collapsed" desc=""Setters"">

    public void setPolyPerimeter(double polyPerimeter) {
        this.polyPerimeter = polyPerimeter;
        perimeter.setText(String.valueOf(formatter.format(polyPerimeter)));
        update();
    }

    public void setPolygonArea(double polygonArea) {
        this.polygonArea = polygonArea;
        polyArea.setText(String.valueOf(formatter.format(polygonArea)));
        update();
    }

    public void setCircumference(double circumference) {
        this.circumference = circumference;
        circum.setText(String.valueOf(formatter.format(circumference)));
        update();
    }

    public void setCircleArea(double circleArea) {
        this.circleArea = circleArea;
        circArea.setText(String.valueOf(formatter.format(circleArea)));
        update();
    }

    // </editor-fold>
    public void setShowCircle(boolean showCircle) {
        this.showCircle = showCircle;

        if (showCircle) {
            circum.setVisible(true);
            circumLabel.setVisible(true);
            circLabel.setVisible(true);
            circArea.setVisible(true);
        } else {
            circum.setVisible(false);
            circumLabel.setVisible(false);
            circLabel.setVisible(false);
            circArea.setVisible(false);
        }
    }

    private void update() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perimeter = new javax.swing.JTextField();
        polyArea = new javax.swing.JTextField();
        circum = new javax.swing.JTextField();
        circArea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        circumLabel = new javax.swing.JLabel();
        circLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(160, 314));
        setMinimumSize(new java.awt.Dimension(160, 314));
        setPreferredSize(new java.awt.Dimension(160, 314));

        perimeter.setEditable(false);
        perimeter.setColumns(8);
        perimeter.setDragEnabled(false);

        polyArea.setEditable(false);
        polyArea.setColumns(8);

        circum.setEditable(false);
        circum.setColumns(8);

        circArea.setEditable(false);
        circArea.setColumns(8);

        jLabel2.setText("Perimeter");

        jLabel3.setText("Polygon Area");

        circumLabel.setText("Circumference");

        circLabel.setText("Circle Area");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(perimeter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(polyArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(circum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(circArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(circLabel)
                    .add(circumLabel)
                    .add(jLabel3))
                .add(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(perimeter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(9, 9, 9)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(polyArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(circumLabel)
                .add(7, 7, 7)
                .add(circum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(circLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(circArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField circArea;
    private javax.swing.JLabel circLabel;
    private javax.swing.JTextField circum;
    private javax.swing.JLabel circumLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField perimeter;
    private javax.swing.JTextField polyArea;
    // End of variables declaration//GEN-END:variables
}
