/*PolygonFrame.java
 * 
 * Javier Chavez
 * jchavez589@cnm.edu
 * 
 * CIS 2275 Java Programming 1 
 * 
 * Program 7: polygons
 * DUE Nov8 2012
 * 
 */
package chavezp7;

import java.awt.Color;

/**
 *
 * @author youracow
 */
public class PolygonFrame extends javax.swing.JFrame {

    private int sides;
    private int radius;
    private boolean circumscribe;

    private Color circleColor;
    private PolygonCalc calculator;

    /**
     * Creates new form PolygonFrame
     */
    public PolygonFrame() {
        initComponents();        
        //init drawing
        sides = 3;
        radius = 1;
        circumscribe = true;
        circleColor = Color.BLUE;

        //set calculator
        calculator = new PolygonCalc(sides, radius);

        //MUST BE DONE first!!! otherwise form values will not be set.
        controlPanel1.setFrame(this);
        //set values in control panel
        controlPanel1.setSides(sides);
        controlPanel1.setColor(circleColor);
        controlPanel1.setRadius(radius);
        controlPanel1.setShowCircle(circumscribe);
        drawPanel1.repaint();

    }
// <editor-fold defaultstate="collapsed" desc="Setters">
    public void setSides(int sides) {
        this.sides = sides;
        update();
    }

    public void setRadius(int radius) {
        this.radius = radius;
        update();
    }

    public void setCircumscribe(boolean circumscribe) {
        this.circumscribe = circumscribe;
        update();
    }

    public void setCircleColor(Color circleColor) {
        this.circleColor = circleColor;
        update();
    }
// </editor-fold>
    
    private void update() {
        //set information for image in drawpanel
        drawPanel1.setRadius(radius);
        drawPanel1.setNumberOfSides(sides);
        drawPanel1.setCircle(circumscribe);
        drawPanel1.setCircleColor(circleColor);

        //set calculator values
        calculator.setNumberOfSides(sides);
        calculator.setRadius(radius);

        //set information to show result of calculations
        infoPanel1.setPolygonArea(calculator.getPolygonArea());
        infoPanel1.setPolyPerimeter(calculator.getPerimeter());
        infoPanel1.setCircleArea(calculator.getCircleArea());
        infoPanel1.setCircumference(calculator.getCircumference());
        infoPanel1.setShowCircle(circumscribe);
        infoPanel1.setRadius(radius);
        infoPanel1.setSides(sides);
        
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel1 = new chavezp7.ControlPanel();
        drawPanel1 = new chavezp7.DrawPanel();
        infoPanel1 = new chavezp7.InfoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        controlPanel1.setBackground(new java.awt.Color(204, 204, 255));

        org.jdesktop.layout.GroupLayout drawPanel1Layout = new org.jdesktop.layout.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 326, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 331, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(controlPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(drawPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(infoPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(controlPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(infoPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 17, Short.MAX_VALUE))
                    .add(drawPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolygonFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chavezp7.ControlPanel controlPanel1;
    private chavezp7.DrawPanel drawPanel1;
    private chavezp7.InfoPanel infoPanel1;
    // End of variables declaration//GEN-END:variables
}
