/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdatePanel.java
 *
 * Javier Chavez
 * jchavez589@cnm.edu
 * 
 * Java 1 P8
 */
package user;

import data.DbManager;
import data.Website;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jchavez589
 */
public class UpdatePanel extends javax.swing.JPanel {
    private DbManager db ;
    private Website website;
    private Frame frame;

    /** Creates new form UpdatePanel */
    public UpdatePanel() {
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        alexaRankField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        companyUrlField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yrFoundedField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        companyAssetsField = new javax.swing.JTextField();
        companyNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        alexaRankField.setMinimumSize(new java.awt.Dimension(65, 20));
        alexaRankField.setPreferredSize(new java.awt.Dimension(65, 20));

        jLabel5.setText("Alexa Rank:");

        companyUrlField.setMinimumSize(new java.awt.Dimension(65, 20));
        companyUrlField.setPreferredSize(new java.awt.Dimension(65, 20));

        jLabel4.setText("URL:");

        jLabel2.setText("Founded:");

        yrFoundedField.setToolTipText("MM/DD/YYYY");
        yrFoundedField.setMinimumSize(new java.awt.Dimension(65, 20));
        yrFoundedField.setPreferredSize(new java.awt.Dimension(65, 20));

        jLabel3.setText("Company Assets:");

        companyAssetsField.setMinimumSize(new java.awt.Dimension(65, 20));
        companyAssetsField.setPreferredSize(new java.awt.Dimension(65, 20));

        companyNameField.setMinimumSize(new java.awt.Dimension(65, 20));
        companyNameField.setPreferredSize(new java.awt.Dimension(65, 20));

        jLabel1.setText("Company Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(companyAssetsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))
                                    .addComponent(yrFoundedField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alexaRankField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))
                            .addComponent(companyUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(companyAssetsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yrFoundedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(companyUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(alexaRankField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String id       = Integer.toString(website.getId());
    String name     = companyNameField.getText();
    String yr       = yrFoundedField.getText();
    String assets   = companyAssetsField.getText();
    String url      = companyUrlField.getText();
    String rnk      = alexaRankField.getText();

    try {
        // TODO add your handling code here:
            db.update(new Website(id,name,assets,yr,url,rnk));
            frame.updatedSite();
    } catch (SQLException ex) {
        Logger.getLogger(UpdatePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alexaRankField;
    private javax.swing.JTextField companyAssetsField;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JTextField companyUrlField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField yrFoundedField;
    // End of variables declaration//GEN-END:variables


    /**
     * @param website the website to set
     */
    public void setWebsite(Website website) {
        this.website = website;
        updateFields();
    }

    public void setDb(DbManager db) {
        this.db = db;
    }
    
    private void updateFields()
    {
        companyNameField.setText(website.getCompName());
        yrFoundedField.setText(website.getFounded());
        companyAssetsField.setText(Double.toString(website.getAssets()));
        companyUrlField.setText(website.getUrl());
        alexaRankField.setText(Integer.toString(website.getAlexaRank()));        
    }

    /**
     * @param frame the frame to set
     */
    public void setFrame(Frame frame) {
        this.frame = frame;
    }
}
