/*EJFrame.java
 * 
 * Name:  Javier Chavez
 * Email: jchavez589@cnm.edu
 * P6 Enigma Class
 * 
 * CIS 2235 Java I
 */

/*
 * EJFrame.java
 *
 * Created on Oct 18, 2012, 11:31:54 AM
 */
package chavezp6;

import java.io.File;
import javax.swing.JFileChooser;


/**
 *
 * @author jchavez589
 */
public class EJFrame extends javax.swing.JFrame {
    
    Enigma enigmaMachine;
    /** Creates new form EJFrame */
    public EJFrame() {
        initComponents();
        
        enigmaMachine = new Enigma();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TabbedPaneWrapper = new javax.swing.JTabbedPane();
        encodePanel = new javax.swing.JPanel();
        saveFileBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setKey = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        outKey = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        encodeMsgBtn = new javax.swing.JButton();
        generateOne = new javax.swing.JCheckBox();
        decodePanel = new javax.swing.JPanel();
        readFilebtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputAreaDecode = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        setKeyDecode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 450));

        saveFileBtn.setText("Save File");
        saveFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Set Key");

        jLabel3.setText("Or");

        jLabel4.setText("Enter Message");

        setKey.setToolTipText("Enter 1-50");

        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane2.setViewportView(outputArea);

        jLabel5.setText("Encoded Message");

        jLabel6.setText("Key");

        encodeMsgBtn.setText("Encode");
        encodeMsgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encodeMsgBtnActionPerformed(evt);
            }
        });

        generateOne.setText("Generate one for me");

        javax.swing.GroupLayout encodePanelLayout = new javax.swing.GroupLayout(encodePanel);
        encodePanel.setLayout(encodePanelLayout);
        encodePanelLayout.setHorizontalGroup(
            encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encodePanelLayout.createSequentialGroup()
                        .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(encodeMsgBtn)
                            .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encodePanelLayout.createSequentialGroup()
                                .addComponent(saveFileBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outKey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encodePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(generateOne)
                        .addGap(133, 133, 133))
                    .addGroup(encodePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setKey, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(116, 116, 116))
        );
        encodePanelLayout.setVerticalGroup(
            encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encodePanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(setKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(generateOne))
                .addGap(26, 26, 26)
                .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(encodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(encodeMsgBtn)
                        .addComponent(saveFileBtn)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        TabbedPaneWrapper.addTab("Encode", encodePanel);

        readFilebtn.setText("Read File");
        readFilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readFilebtnActionPerformed(evt);
            }
        });

        outputAreaDecode.setColumns(20);
        outputAreaDecode.setRows(5);
        jScrollPane4.setViewportView(outputAreaDecode);

        jLabel8.setText("Decoded Message");

        jLabel10.setText("Key");

        setKeyDecode.setToolTipText("Enter 1-50");
        setKeyDecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setKeyDecodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout decodePanelLayout = new javax.swing.GroupLayout(decodePanel);
        decodePanel.setLayout(decodePanelLayout);
        decodePanelLayout.setHorizontalGroup(
            decodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decodePanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(decodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decodePanelLayout.createSequentialGroup()
                            .addGroup(decodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(readFilebtn)
                                .addComponent(jLabel8))
                            .addGap(71, 71, 71)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decodePanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setKeyDecode, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        decodePanelLayout.setVerticalGroup(
            decodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decodePanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(readFilebtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setKeyDecode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(86, 86, 86))
        );

        TabbedPaneWrapper.addTab("Decode", decodePanel);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Enigma Machine");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabbedPaneWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(TabbedPaneWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encodeMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encodeMsgBtnActionPerformed
        // TODO add your handling code here:

        if (generateOne.isSelected()) {
            enigmaMachine.setMessage(messageArea.getText());
        }
        if(setKey.getText().length() > 0){
            enigmaMachine.setMessage(messageArea.getText(), Integer.parseInt(setKey.getText()));
        }
        outputArea.setText(enigmaMachine.getEncodedMessage());

        outKey.setText(Integer.toString(enigmaMachine.getKey()));

    }//GEN-LAST:event_encodeMsgBtnActionPerformed

    private void readFilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readFilebtnActionPerformed

        String currPath = System.getProperty("user.dir");
 
        JFileChooser filechooser = new JFileChooser(currPath);


        int choice = filechooser.showOpenDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            enigmaMachine.openDoc(file); 
        }
        
        outputAreaDecode.setText(enigmaMachine.getMessage());
        setKeyDecode.setText(Integer.toString(enigmaMachine.getKey()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_readFilebtnActionPerformed

    private void saveFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileBtnActionPerformed
         
    String currPath = System.getProperty("user.dir");
        JFileChooser filechooser = new JFileChooser(currPath);


        int choice = filechooser.showSaveDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            enigmaMachine.saveDoc(file);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveFileBtnActionPerformed

    private void setKeyDecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setKeyDecodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setKeyDecodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPaneWrapper;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel decodePanel;
    private javax.swing.JButton encodeMsgBtn;
    private javax.swing.JPanel encodePanel;
    private javax.swing.JCheckBox generateOne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JTextField outKey;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JTextArea outputAreaDecode;
    private javax.swing.JButton readFilebtn;
    private javax.swing.JButton saveFileBtn;
    private javax.swing.JTextField setKey;
    private javax.swing.JTextField setKeyDecode;
    // End of variables declaration//GEN-END:variables
}
